version: '3'

networks:
  laravel_network:
    driver: bridge

services:
  php:
    container_name: laravel_php
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src/mrm-lara:/var/www:cached
    networks:
      - laravel_network

  nginx:
    container_name: laravel_nginx
    image: nginx
    ports:
      - 8881:80
    volumes:
      - ./src/mrm-lara:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel_network

  db:
    container_name: laravel_mysql
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cobafilament
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - laravel_network

  # mail:
  #   container_name: laravel_mailpit
  #   image: axllent/mailpit:latest
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   networks:
  #     - laravel_network

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadminc
  #   restart: unless-stopped
  #   environment:
  #     PMA_HOST: db  # Use the MySQL service name as the hostname
  #     PMA_PORT: 3306
  #   ports:
  #     - "8882:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel_network

  python-app-dashboard:
    container_name: python_app_dashboard
    build: ./src/mrm-fastapi
    ports:
      - 8009:8009
      - 8050:8050
    volumes:
      - ./src/mrm-fastapi:/app
    environment:
      # app.py
      - MYSQL_DB_HOST=laravel_mysql
      - MYSQL_DB_USER=root
      - MYSQL_DB_PASS=root
      - MYSQL_DB_DATABASE=cobafilament
      - MYSQL_DB_PORT=3306
      - ALLOW_URL_LARAVEL=http://localhost:8000
      # app_dash.py
      - MYSQL_DB_URI=mysql+pymysql://root:root@laravel_mysql:3306/cobafilament
    command: bash -c "/app/setup_new_pyproject.sh"
    depends_on:
      - db
    networks:
      - laravel_network
